# Generated by Django 2.1.5 on 2019-02-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True)),
                ('year_model', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('fiscal_power', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('mark', models.CharField(max_length=30)),
            ],
        ),
    ]
